name: Codespector Review

on:
  pull_request:
    types: [opened, synchronize]

env:
  CODESPECTOR_RESULT_FILE: "codespector/result.md"
  CODESPECTOR_COMBINED_FILE: "codespector/combined.json"
  ENV_VAR: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  codespector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print Environment Variables and Secrets
        env:
          CODESPECTOR_CHAT_TOKEN: ${{ vars.CODESPECTOR }}
          CODESPECTOR_SYSTEM_CONTENT: ${{ secrets.CODESPECTOR_SYSTEM_CONTENT }}
          CODESPECTOR_PROMPT_CONTENT: ${{ secrets.CODESPECTOR_PROMPT_CONTENT }}
          CODESPECTOR_RESULT_FILE: ${{ secrets.CODESPECTOR_RESULT_FILE }}
          CODESPECTOR_CHAT_AGENT: ${{ secrets.CODESPECTOR_CHAT_AGENT }}
        run: |
          env | grep CODESPECTOR
          echo "Secret CODESPECTOR_CHAT_TOKEN: $CODESPECTOR_CHAT_TOKEN"
          echo "Secret CODESPECTOR_SYSTEM_CONTENT: $CODESPECTOR_SYSTEM_CONTENT"
          echo "Secret CODESPECTOR_PROMPT_CONTENT: $CODESPECTOR_PROMPT_CONTENT"
          echo "Secret CODESPECTOR_RESULT_FILE: $CODESPECTOR_RESULT_FILE"
          echo "Secret CODESPECTOR_CHAT_AGENT: $CODESPECTOR_CHAT_AGENT"
