name: Codespector Review

on:
  pull_request:
    types: [opened, synchronize]

env:
  CODESPECTOR_RESULT_FILE: "codespector/result.md"
  CODESPECTOR_COMBINED_FILE: "codespector/combined.json"
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  codespector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Codespector
        env:
          CODESPECTOR_CHAT_TOKEN: ${{ secrets.CODESPECTOR_CHAT_TOKEN }}
          CODESPECTOR_SYSTEM_CONTENT: ${{ secrets.CODESPECTOR_SYSTEM_CONTENT }}
          CODESPECTOR_PROMPT_CONTENT: ${{ secrets.CODESPECTOR_PROMPT_CONTENT }}
          CODESPECTOR_RESULT_FILE: ${{ secrets.CODESPECTOR_RESULT_FILE }}
          CODESPECTOR_CHAT_AGENT: ${{ secrets.CODESPECTOR_CHAT_AGENT }}
        run: |
          echo "repository variable : $CODESPECTOR_CHAT_TOKEN"
          echo "organization variable : $CODESPECTOR_SYSTEM_CONTENT"
          echo "overridden variable : $CODESPECTOR_PROMPT_CONTENT"
          echo "variable from shell environment : $env_var"
